version: '3.9'

services:
  web:
    command: uvicorn django_base.asgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG=False
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web