version: '3.9'

services:
  web:
    volumes:
      - ./django_base:/app
    command: >
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m uvicorn django_base.asgi:application --host 0.0.0.0 --port 8000
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "5678:5678"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db 